package main

import("context";"crypto/tls";"crypto/x509";"encoding/json";"errors";"flag";"fmt";"io";"net";"net/http";"net/url";"regexp";"sort";"strings";"sync";"time")

type Report struct{Target string `json:"target"`; GeneratedAt time.Time `json:"generated_at"`; HTTP HTTPInfo `json:"http"`; DNS DNSInfo `json:"dns"`; TLS *TLSInfo `json:"tls,omitempty"`; RDAP *RDAPInfo `json:"rdap,omitempty"`; Network *NetworkInfo `json:"network,omitempty"`; Technologies []string `json:"technologies,omitempty"`; Trackers []string `json:"trackers,omitempty"`; Security map[string]string `json:"security"`; Subdomains []string `json:"subdomains,omitempty"`; Resources Resources `json:"resources"`; Errors []string `json:"errors,omitempty"`}
type HTTPInfo struct{Status string `json:"status"`; StatusCode int `json:"status_code"`; FinalURL string `json:"final_url"`; Server string `json:"server,omitempty"`; ContentType string `json:"content_type,omitempty"`; ResponseTime int64 `json:"response_time_ms"`; Headers map[string]string `json:"selected_headers,omitempty"`}
type DNSInfo struct{A,AAAA,MX,NS,TXT []string}
type TLSInfo struct{Version,Subject,Issuer string; Expires time.Time; DNSNames []string; Valid,SelfSigned bool}
type RDAPInfo struct{Handle string; Status []string; Registrar string; Nameservers []string; Events []string}
type NetworkInfo struct{IP,Country,City,ASN,Organization,Hostname string}
type Resources struct{Robots bool `json:"robots_txt"`; Sitemap bool `json:"sitemap_xml"`}
type rdapResponse struct{Handle string `json:"handle"`; Status []string `json:"status"`; Entities []struct{Roles []string `json:"roles"`; VCardArray []any `json:"vcardArray"`} `json:"entities"`; Nameservers []struct{LdhName string `json:"ldhName"`} `json:"nameservers"`; Events []struct{EventAction,EventDate string} `json:"events"`}
var httpClient=&http.Client{Timeout:12*time.Second,CheckRedirect:func(req *http.Request,via []*http.Request)error{if len(via)>=8{return errors.New("too many redirects")};return nil}}
func main(){jsonOut:=flag.Bool("json",false,"write JSON report");full:=flag.Bool("full",false,"run extended public OSINT checks");flag.Parse();if flag.NArg()!=1{fmt.Println("usage: web-osint [--json] [--full] <domain-or-url>");return};r:=analyze(flag.Arg(0),*full);if *jsonOut{b,_:=json.MarshalIndent(r,"","  ");fmt.Println(string(b));return};printReport(r)}
func analyze(target string,full bool)Report{raw:=strings.TrimSpace(target);if !strings.Contains(raw,"://"){raw="https://"+raw};u,e:=url.Parse(raw);if e!=nil||u.Hostname()==""{return Report{Target:target,GeneratedAt:time.Now(),Errors:[]string{"invalid target"}}};h:=strings.ToLower(strings.TrimSuffix(u.Hostname(),"."));r:=Report{Target:h,GeneratedAt:time.Now(),Security:map[string]string{}};r.HTTP=inspectHTTP(raw);r.DNS=inspectDNS(h);if strings.HasPrefix(r.HTTP.FinalURL,"https://")||strings.HasPrefix(raw,"https://"){r.TLS=inspectTLS(h)};r.Technologies,r.Trackers=inspectHTML(r.HTTP.FinalURL);r.Security=securityHeaders(r.HTTP.Headers);if full{var w sync.WaitGroup;w.Add(4);go func(){defer w.Done();r.RDAP=inspectRDAP(h)}();go func(){defer w.Done();r.Network=inspectNetwork(r.DNS.A)}();go func(){defer w.Done();r.Subdomains=inspectCT(h)}();go func(){defer w.Done();r.Resources=inspectResources(h)}();w.Wait()};return r}
func inspectHTTP(raw string)HTTPInfo{req,e:=http.NewRequest(http.MethodGet,raw,nil);if e!=nil{return HTTPInfo{Status:e.Error()}};req.Header.Set("User-Agent","web-osint/0.2 (+https://github.com/aaron0sec/web-osint)");st:=time.Now();resp,e:=httpClient.Do(req);if e!=nil&&strings.HasPrefix(raw,"https://"){raw="http://"+strings.TrimPrefix(raw,"https://");req,_=http.NewRequest(http.MethodGet,raw,nil);req.Header.Set("User-Agent","web-osint/0.2");st=time.Now();resp,e=httpClient.Do(req)};if e!=nil{return HTTPInfo{Status:e.Error(),ResponseTime:time.Since(st).Milliseconds()}};defer resp.Body.Close();_,_=io.ReadAll(io.LimitReader(resp.Body,2<<20));hs:=map[string]string{};for _,k:=range []string{"Server","Content-Type","Location","Strict-Transport-Security","Content-Security-Policy","X-Frame-Options","X-Content-Type-Options","Referrer-Policy","Permissions-Policy"}{if v:=resp.Header.Get(k);v!=""{hs[k]=v}};return HTTPInfo{Status:resp.Status,StatusCode:resp.StatusCode,FinalURL:resp.Request.URL.String(),Server:resp.Header.Get("Server"),ContentType:resp.Header.Get("Content-Type"),ResponseTime:time.Since(st).Milliseconds(),Headers:hs}}
func inspectHTML(raw string)([]string,[]string){if raw==""{return nil,nil};req,_:=http.NewRequest(http.MethodGet,raw,nil);req.Header.Set("User-Agent","web-osint/0.2");resp,e:=httpClient.Do(req);if e!=nil{return nil,nil};defer resp.Body.Close();b,_:=io.ReadAll(io.LimitReader(resp.Body,4<<20));s:=strings.ToLower(string(b));sig:=map[string][]string{"WordPress":{"wp-content","wp-includes","wordpress"},"Next.js":{"__next_data__","/_next/"},"React":{"data-reactroot","react.production.min.js","react-dom"},"Vue.js":{"vue.js","__vue__","data-v-"},"Angular":{"ng-version","angular.min.js"},"Bootstrap":{"bootstrap.min.css","bootstrap.min.js"},"jQuery":{"jquery.min.js","jquery.js"},"Google Tag Manager":{"googletagmanager.com/gtm.js","gtag/js"},"Cloudflare":{"cf-ray","__cf_bm"}};found:=map[string]bool{};for n,ps:=range sig{for _,p:=range ps{if strings.Contains(s,p){found[n]=true;break}}};tech:=[]string{};for n:=range found{tech=append(tech,n)};sort.Strings(tech);tp:=map[string][]string{"Google Analytics":{"google-analytics.com","googletagmanager.com"},"Meta Pixel":{"connect.facebook.net","fbq("},"Matomo":{"matomo.js","piwik.js"},"Hotjar":{"hotjar.com"},"Microsoft Clarity":{"clarity.ms"}};tr:=[]string{};for n,ps:=range tp{for _,p:=range ps{if strings.Contains(s,p){tr=append(tr,n);break}}};sort.Strings(tr);return tech,tr}
func inspectDNS(h string)DNSInfo{ctx,c:=context.WithTimeout(context.Background(),6*time.Second);defer c();d:=DNSInfo{};if x,_:=net.DefaultResolver.LookupIP(ctx,"ip",h);len(x)>0{for _,ip:=range x{if ip.To4()!=nil{d.A=uniq(d.A,ip.String())}else{d.AAAA=uniq(d.AAAA,ip.String())}}};if x,_:=net.DefaultResolver.LookupMX(ctx,h);len(x)>0{for _,v:=range x{d.MX=uniq(d.MX,strings.TrimSuffix(v.Host,"."))}};if x,_:=net.DefaultResolver.LookupNS(ctx,h);len(x)>0{for _,v:=range x{d.NS=uniq(d.NS,strings.TrimSuffix(v.Host,"."))}};if x,_:=net.DefaultResolver.LookupTXT(ctx,h);len(x)>0{d.TXT=x};return d}
func inspectTLS(h string)*TLSInfo{c,e:=tls.DialWithDialer(&net.Dialer{Timeout:6*time.Second},"tcp",net.JoinHostPort(h,"443"),&tls.Config{ServerName:h,MinVersion:tls.VersionTLS12});if e!=nil{return nil};defer c.Close();st:=c.ConnectionState();if len(st.PeerCertificates)==0{return nil};x:=st.PeerCertificates[0];valid:=x.NotBefore.Before(time.Now())&&x.NotAfter.After(time.Now());verified:=false;if p,e:=x509.SystemCertPool();e==nil&&p!=nil{verified=true};return &TLSInfo{Version:tlsVersion(st.Version),Subject:x.Subject.String(),Issuer:x.Issuer.String(),Expires:x.NotAfter,DNSNames:x.DNSNames,Valid:valid,SelfSigned:x.Issuer.String()==x.Subject.String()&&!verified}}
func inspectRDAP(h string)*RDAPInfo{req,_:=http.NewRequest(http.MethodGet,"https://rdap.org/domain/"+url.PathEscape(h),nil);req.Header.Set("Accept","application/rdap+json, application/json");resp,e:=httpClient.Do(req);if e!=nil||resp.StatusCode>=400{return nil};defer resp.Body.Close();var d rdapResponse;if json.NewDecoder(io.LimitReader(resp.Body,2<<20)).Decode(&d)!=nil{return nil};r:=&RDAPInfo{Handle:d.Handle,Status:d.Status};for _,n:=range d.Nameservers{if n.LdhName!=""{r.Nameservers=append(r.Nameservers,n.LdhName)}};for _,v:=range d.Events{if v.EventAction!=""{r.Events=append(r.Events,v.EventAction+": "+v.EventDate)}};for _,ent:=range d.Entities{for _,role:=range ent.Roles{if role=="registrar"{r.Registrar=vcardName(ent.VCardArray)}}};return r}
func vcardName(v []any)string{b,_:=json.Marshal(v);m:=regexp.MustCompile(`(?i)"fn"\s*,\s*\[?"?([^"\],]+)`).FindStringSubmatch(string(b));if len(m)>1{return strings.TrimSpace(m[1])};return ""}
func inspectNetwork(ips []string)*NetworkInfo{if len(ips)==0{return nil};req,_:=http.NewRequest(http.MethodGet,"https://ipwho.is/"+url.PathEscape(ips[0]),nil);resp,e:=httpClient.Do(req);if e!=nil||resp.StatusCode>=400{return nil};defer resp.Body.Close();var d struct{Success bool `json:"success"`;IP,Country,City,Hostname string;Connection struct{ASN int `json:"asn"`;Org string `json:"org"`} `json:"connection"`};if json.NewDecoder(io.LimitReader(resp.Body,1<<20)).Decode(&d)!=nil||!d.Success{return nil};return &NetworkInfo{IP:d.IP,Country:d.Country,City:d.City,ASN:fmt.Sprintf("AS%d",d.Connection.ASN),Organization:d.Connection.Org,Hostname:d.Hostname}}
func inspectCT(h string)[]string{req,_:=http.NewRequest(http.MethodGet,"https://crt.sh/?q=%25."+url.QueryEscape(h)+"&output=json",nil);resp,e:=httpClient.Do(req);if e!=nil||resp.StatusCode>=400{return nil};defer resp.Body.Close();var rows []struct{NameValue string `json:"name_value"`};if json.NewDecoder(io.LimitReader(resp.Body,8<<20)).Decode(&rows)!=nil{return nil};out:=[]string{};for _,row:=range rows{for _,n:=range strings.Split(row.NameValue,"\n"){n=strings.TrimPrefix(strings.ToLower(strings.TrimSpace(n)),"*.");if n==h||strings.HasSuffix(n,"."+h){out=uniq(out,n)}}};sort.Strings(out);return out}
func inspectResources(h string)Resources{c:=&http.Client{Timeout:8*time.Second,CheckRedirect:func(req *http.Request,via []*http.Request)error{if len(via)>5{return http.ErrUseLastResponse};return nil}};return Resources{Robots:exists(c,"https://"+h+"/robots.txt"),Sitemap:exists(c,"https://"+h+"/sitemap.xml")}}
func exists(c *http.Client,u string)bool{req,_:=http.NewRequest(http.MethodHead,u,nil);req.Header.Set("User-Agent","web-osint/0.2");resp,e:=c.Do(req);if e!=nil{return false};resp.Body.Close();return resp.StatusCode>=200&&resp.StatusCode<400}
func securityHeaders(h map[string]string)map[string]string{o:=map[string]string{};for _,k:=range []string{"Strict-Transport-Security","Content-Security-Policy","X-Frame-Options","X-Content-Type-Options","Referrer-Policy","Permissions-Policy"}{if v:=h[k];v!=""{o[k]=v}else{o[k]="missing"}};return o}
func tlsVersion(v uint16)string{switch v{case tls.VersionTLS13:return "TLS 1.3";case tls.VersionTLS12:return "TLS 1.2";default:return fmt.Sprintf("0x%x",v)}}
func uniq(v []string,s string)[]string{for _,x:=range v{if x==s{return v}};return append(v,s)}
func join(v []string)string{if len(v)==0{return "-"};return strings.Join(v,", ")};func val(v string)string{if v==""{return "-"};return v}
func printReport(r Report){fmt.Printf("web-osint 0.2 — public web intelligence\n\nTarget: %s\n\nHTTP\n  Status:       %s\n  Final URL:    %s\n  Server:       %s\n  Response:     %d ms\n\nDNS\n  A:            %s\n  AAAA:         %s\n  MX:            %s\n  NS:            %s\n",r.Target,r.HTTP.Status,val(r.HTTP.FinalURL),val(r.HTTP.Server),r.HTTP.ResponseTime,join(r.DNS.A),join(r.DNS.AAAA),join(r.DNS.MX),join(r.DNS.NS));if r.TLS!=nil{fmt.Printf("\nTLS\n  Version:       %s\n  Issuer:        %s\n  Expires:       %s\n  Valid:         %t\n",r.TLS.Version,r.TLS.Issuer,r.TLS.Expires.Format(time.RFC3339),r.TLS.Valid)};if r.RDAP!=nil{fmt.Printf("\nRDAP\n  Handle:        %s\n  Registrar:     %s\n  Status:        %s\n  Nameservers:   %s\n",val(r.RDAP.Handle),val(r.RDAP.Registrar),join(r.RDAP.Status),join(r.RDAP.Nameservers))};if r.Network!=nil{fmt.Printf("\nNETWORK\n  IP:            %s\n  ASN:           %s\n  Organization:  %s\n  Country:       %s\n  City:          %s\n",r.Network.IP,val(r.Network.ASN),val(r.Network.Organization),val(r.Network.Country),val(r.Network.City))};fmt.Printf("\nTechnologies: %s\nTrackers:     %s\n\nSecurity headers\n",join(r.Technologies),join(r.Trackers));ks:=[]string{};for k:=range r.Security{ks=append(ks,k)};sort.Strings(ks);for _,k:=range ks{fmt.Printf("  %-28s %s\n",k+":",r.Security[k])};if len(r.Subdomains)>0{fmt.Printf("\nCertificate Transparency subdomains (%d)\n  %s\n",len(r.Subdomains),join(r.Subdomains))};fmt.Printf("\nResources\n  robots.txt:   %t\n  sitemap.xml:  %t\n\nTraffic: authoritative visitor counts are not inferred. Public estimates will only be added when backed by a documented measurement source.\n",r.Resources.Robots,r.Resources.Sitemap)}
